add title to german pages, fix de/en link for models
OCR-D/ocrd-website pull request #224
Opened 2021-05-31 08:14 UTC by kba

2021-05-31 08:40 UTC, mweidling requested changes
Danke dir, dass du das gleich umgesetzt hast! :) Ich habe nur ein paar Rückmeldungen zur Rechtschreibung. Komposita der Art "OCR-D-xyz" würde ich immer mit Bindestrich schreiben.

2021-05-31 08:40 UTC, mweidling commented on site/de/about.md
> +title: Das OCR-D Projekt
OCR-D-Projekt

2021-05-31 08:40 UTC, mweidling commented on site/de/contact.md
> +title: Das OCR-D Team
OCR-D-Team

2021-05-31 08:40 UTC, mweidling commented on site/de/dita.md
> +title: OCR-D: Anforderungsprofil für die Dokumentation der Modul Projekte
Heißt es "Modu Projekte" oder "Modulprojekte"? (Ich bin mir hier auch nicht immer ganz sicher…)

2021-05-31 08:40 UTC, mweidling commented on site/de/plattformen.md
> +title: OCR-D Kanäle und Plattformen
OCR-D-Kanäle und -Plattformen

2021-06-02 06:19 UTC, EEngl52 approved these changes
Great, thx!

@mweidling you definitly have a point. Headings are not the only place where we haven't used `-` consistently though. so perhaps we should rather make a separate PR which takes care of all the composita

2021-06-02 06:19 UTC, EEngl52 commented on site/de/dita.md
> +title: OCR-D: Anforderungsprofil für die Dokumentation der Modul Projekte
```suggestion
title: OCR-D: Anforderungsprofil für die Dokumentation der Modulprojekte 
```

2021-06-02 06:19 UTC, EEngl52 commented on site/de/dita.md
> +title: OCR-D: Anforderungsprofil für die Dokumentation der Modul Projekte
well spotted!

2021-06-02 11:57 UTC, mweidling approved these changes

2021-08-02 15:21 UTC, merged