add bibtag post
OCR-D/ocrd-website pull request #228
Opened 2021-06-10 15:00 UTC by EEngl52

2021-06-10 22:35 UTC, bertsky requested changes
thx

2021-06-10 22:35 UTC, bertsky commented on site/de/_posts/2021-06-11-bibtag.md
> +einbringen.
```suggestion
```suggestion
[berichten](https://wrznr.github.io/bibliothekartag-2021) von ihren Erfahrungen bei Aufbau und Begleitung einer kollaborativen Transkriptionsinitiative an der SLUB Dresden zur Erstellung von OCR-Trainingsmaterial und -Modellen
mithilfe von OCR-D und niedrigschwelliger Annotationswerkzeuge.
```
```

2021-06-10 22:35 UTC, bertsky commented on site/en/_posts/2021-06-11-bibtag.md
> +report on their experiences from a collaborative transcription initiative in which SLUB Dresden staff have been involved for a year.
```suggestion
[Elisabeth Engl](https://dbt2021.abstractserver.com/program/#/details/presentations/70) describes the current status of
the OCR-D software and gives an outlook on the many planned application scenarios, which are at the centre of the third project phase. 
[Kay-Michael Würzner and Robert Sachunsky](https://dbt2021.abstractserver.com/program/#/details/presentations/184)
[report](https://wrznr.github.io/bibliothekartag-2021) on their experiences with setting up and conducting a collaborative transcription initiative at SLUB Dresden to create OCR training material and models by means of OCR-D and low-threshold annotation tools.
```

2021-06-11 07:38 UTC, MareenGeestmann approved these changes

2021-06-11 08:20 UTC, EEngl52 commented on site/de/_posts/2021-06-11-bibtag.md
> +OCR-D ist auch auf dem diesjährigen Bibliothekartag vertreten, der vom 16.-18. Juni virtuell sowie an zwei Tagen auch vor Ort in Bremen
```suggestion
OCR-D ist auch auf dem diesjährigen Bibliothekartag vertreten, der vom 16.-18. Juni 2021 virtuell sowie an zwei Tagen auch vor Ort in Bremen 
```

2021-06-11 10:08 UTC, EEngl52 commented on site/de/_posts/2021-06-11-bibtag.md
> +einbringen.
```suggestion
[berichten](https://wrznr.github.io/bibliothekartag-2021) von ihren Erfahrungen bei Aufbau und Begleitung einer kollaborativen Transkriptionsinitiative an der SLUB Dresden zur Erstellung von OCR-Trainingsmaterial und -Modellen mithilfe von OCR-D und niedrigschwelliger Annotationswerkzeuge.
```

2021-06-11 10:10 UTC, merged